import type { GuideLanguage } from "./guide-language";
export type GuidePage = "home" | "upload" | "library" | "review" | "classes" | "insights" | "plan" | "lesson-notes" | "lesson-ask" | "lesson-practice" | "lesson-transcript" | "lesson-sources" | "lesson-catchup" | "dictionary";
type Copy = readonly [string,string];
export type GuideStep = {selector:string;copy:Record<GuideLanguage,Copy>};
const step=(selector:string,en:Copy,ar:Copy,ur:Copy):GuideStep=>({selector,copy:{en,ar,ur}});
const lessonSource=step('[data-tour="home-source"]',["Choose your lesson.","Select a ready recording here. Your questions, notes and practice use that lesson."],["اختر درسك.","اختر تسجيلاً جاهزاً هنا. تستخدم الأسئلة والملاحظات والمراجعة هذا الدرس."],["اپنا سبق منتخب کریں۔","یہاں تیار ریکارڈنگ منتخب کریں۔ سوالات، نوٹس اور مشق اسی سبق سے ہوں گے۔"]);
const recording=step('[data-tour="home-entry"]',["Record or upload.","Record permitted class audio, or upload a recording you already have. We’ll prepare your notes and practice."],["سجّل أو ارفع تسجيلاً.","سجّل صوت الدرس المسموح به أو ارفع تسجيلاً لديك. سنعدّ الملاحظات والمراجعة."],["ریکارڈ یا اپ لوڈ کریں۔","اجازت کے ساتھ کلاس کی آڈیو ریکارڈ کریں یا موجودہ ریکارڈنگ اپ لوڈ کریں۔ نوٹس اور مشق تیار ہو جائیں گے۔"]);
const composer=step('[data-tour="home-composer"]',["Ask about this lesson.","Answers use your selected lesson only. Check the supporting text and audio. Ask a qualified teacher for religious guidance."],["اسأل عن هذا الدرس.","تستخدم الإجابات الدرس المحدّد فقط. راجع النص والصوت الداعمين. اسأل معلّماً مؤهّلاً للإرشاد الديني."],["اسی سبق کے بارے میں پوچھیں۔","جوابات صرف منتخب سبق سے آتے ہیں۔ متعلقہ متن اور آڈیو دیکھیں۔ دینی رہنمائی کے لیے مستند استاد سے پوچھیں۔"]);
const tabs=step('[data-tour="lesson-tabs"]',["One lesson, a few ways to learn.","Move between notes, class questions, practice and transcript. Reference lookup stays separate from lesson answers."],["درس واحد وطرق متعددة للتعلّم.","تنقّل بين الملاحظات والأسئلة والمراجعة والنص. يبقى البحث عن المراجع منفصلاً عن إجابات الدرس."],["ایک سبق، سیکھنے کے چند طریقے۔","نوٹس، سوالات، مشق اور متن کے درمیان جائیں۔ حوالہ تلاش کرنا سبق کے جوابات سے الگ رہتا ہے۔"]);
export const pageGuides:Record<GuidePage,GuideStep[]>={
 home:[recording,lessonSource,composer],
 dictionary:[step('[data-tour="dictionary-search"]',["Find your teacher’s explanation.","Search terms or explanations across your lessons. Different recordings stay separate."],["ابحث عن شرح معلّمك.","ابحث عن المصطلحات والشروح في دروسك. يبقى كل تسجيل مستقلاً."],["اپنے استاد کی وضاحت تلاش کریں۔","اپنے اسباق میں اصطلاحات اور وضاحتیں تلاش کریں۔ ہر ریکارڈنگ الگ رہتی ہے۔"]),step('[data-tour="dictionary-entries"]',["Replay before memorising.","Term spellings can be wrong. Read the captured words and listen to their source."],["استمع قبل الحفظ.","قد تُكتب المصطلحات خطأ. اقرأ الكلمات المنقولة واستمع إلى مصدرها."],["یاد کرنے سے پہلے سنیں۔","اصطلاح کی املا غلط ہو سکتی ہے۔ اصل الفاظ پڑھیں اور آڈیو سنیں۔"])],
 "lesson-catchup":[tabs],
 upload:[step('[data-tour="upload-drop"]',["Start with your audio.","Choose a permitted fictional recording for this contest demo. Next, name the lesson and choose your note detail."],["ابدأ بالتسجيل الصوتي.","اختر تسجيلاً خيالياً مسموحاً به لعرض المسابقة. ثم سمّ الدرس وحدّد تفاصيل الملاحظات."],["اپنی آڈیو سے شروع کریں۔","اس مقابلے کے ڈیمو کے لیے اجازت یافتہ فرضی ریکارڈنگ منتخب کریں۔ پھر سبق کا نام اور نوٹس کی تفصیل منتخب کریں۔"]),step('[data-tour="upload-recent"]',["Come back when it’s ready.","Your uploads stay here while they prepare. Open a ready lesson to read, ask questions and practise."],["عد عندما يصبح الدرس جاهزاً.","تبقى تسجيلاتك هنا أثناء إعدادها. افتح الدرس الجاهز للقراءة وطرح الأسئلة والمراجعة."],["تیار ہونے پر واپس آئیں۔","تیاری کے دوران آپ کی ریکارڈنگ یہاں رہتی ہے۔ تیار سبق کھول کر پڑھیں، سوال کریں اور مشق کریں۔"])],
 plan:[step('[data-tour="plan-heading"]',["A path through your lessons.","The plan uses your prepared recording, its supported topics and your saved practice. Open a topic to hear its source, read or try a question."],["خطة لدروسك.","تستخدم الخطة تسجيلك الجاهز وموضوعاته الموثقة ومراجعتك المحفوظة. افتح موضوعاً لسماع مصدره أو قراءته أو تجربة سؤال."],["اپنے اسباق کا راستہ۔","یہ منصوبہ تیار ریکارڈنگ، اس کے مستند موضوعات اور آپ کی محفوظ مشق استعمال کرتا ہے۔ اصل آواز سننے، پڑھنے یا سوال آزمانے کے لیے موضوع کھولیں۔"])],
 library:[step('[data-tour="lessons-toolbar"]',["Find a lesson.","Search by title or course. Switch between your recordings and lessons shared with you."],["ابحث عن درس.","ابحث بالعنوان أو المادة. تنقّل بين تسجيلاتك والدروس التي شاركها زملاؤك معك."],["سبق تلاش کریں۔","عنوان یا مضمون سے تلاش کریں۔ اپنی ریکارڈنگ اور آپ کے ساتھ شیئر کیے گئے اسباق دیکھیں۔"]),step('[data-tour="lessons-content"]',["Pick up where you left off.","Open a lesson for its notes, original audio and practice. Preparing recordings stay here until they are ready."],["تابع دروسك.","افتح درساً لقراءة الملاحظات وسماع التسجيل الأصلي والمراجعة. تبقى التسجيلات هنا أثناء إعدادها."],["اپنا سبق جاری رکھیں۔","نوٹس، اصل آڈیو اور مشق کے لیے سبق کھولیں۔ ریکارڈنگ تیار ہونے تک یہیں رہتی ہے۔"])],
 review:[step('[data-tour="review-summary"]',["Return to what you’ve tried.","Missed points return sooner. Open a due review to try it again and hear the lesson behind the answer."],["راجع ما حاولت تذكّره.","تظهر الأسئلة والبطاقات المحفوظة هنا. تعود النقاط التي فاتتك في وقت أقرب؛ افتح المراجعة للعودة إلى الدرس."],["جو آزمایا ہے اسے دہرائیں۔","محفوظ سوالات اور کارڈ یہاں آئیں گے۔ چھوٹے ہوئے نکات جلد واپس آئیں گے؛ دوبارہ مشق کے لیے Review کھولیں۔"]),step('[data-tour="review-start"]',["Pick how to practise.","Choose Quiz or Flashcards for feedback as you go, or take a Lesson test and see answers at the end."],["اختر طريقة المراجعة.","جرّب مراجعة قصيرة مع التصحيح أو اختباراً من الدرس وتظهر الإجابات في النهاية."],["مشق کا طریقہ منتخب کریں۔","جواب کے ساتھ مختصر مشق کریں، یا سبق کا ٹیسٹ دیں اور آخر میں جواب دیکھیں۔"])],
 classes:[step('[data-tour="classes-create"]',["Create your private class.","Name a class for your study circle. The class owner can make an invitation that works once and expires in 24 hours."],["أنشئ صفّك الخاص.","سمّ صفّاً لمجموعة الدراسة. يمكن لصاحب الصف إنشاء دعوة تُستخدم مرة واحدة وتنتهي خلال ٢٤ ساعة."],["اپنی نجی کلاس بنائیں۔","مطالعے کے گروپ کا نام رکھیں۔ کلاس بنانے والا ایک بار استعمال ہونے والا دعوتی لنک بنا سکتا ہے، جو ۲۴ گھنٹے بعد ختم ہو جاتا ہے۔"]),step('[data-tour="classes-content"]',["Catch up with classmates.","Share only recordings you have permission to share. Classmates can open the lesson; your practice responses stay private."],["تابع الدروس مع زملائك.","شارك فقط التسجيلات التي لديك إذن بمشاركتها. يمكن للزملاء فتح الدرس، وتبقى إجابات المراجعة خاصة بك."],["ہم جماعتوں کے ساتھ سبق دہرائیں۔","صرف وہ ریکارڈنگ شیئر کریں جس کی اجازت ہو۔ ہم جماعت سبق کھول سکتے ہیں؛ آپ کی مشق کے جوابات نجی رہتے ہیں۔"])],
 insights:[step('[data-tour="insights-summary"]',["Your actual study activity.","These counts use your saved lessons and responses. Missed points help you decide what to revisit; they are not a religious knowledge score."],["نشاطك الدراسي الفعلي.","تُحسب هذه الأرقام من الدروس والإجابات المحفوظة. تساعد النقاط التي فاتتك على اختيار ما تراجعه، وليست مقياساً للعلم الديني."],["آپ کی اصل مطالعے کی سرگرمی۔","یہ اعداد محفوظ اسباق اور جوابات سے آتے ہیں۔ مشکل نکات اگلی مشق منتخب کرنے میں مدد دیتے ہیں، دینی علم کا اسکور نہیں ہیں۔"]),step('[data-tour="insights-next"]',["Choose your next review.","Start with a missed point or open Review. The activity calendar records new saved attempts; earlier reviews may have no dates."],["اختر مراجعتك التالية.","ابدأ بنقطة فاتتك أو افتح المراجعة. يسجّل التقويم المحاولات الجديدة المحفوظة؛ قد لا توجد تواريخ للمراجعات السابقة."],["اگلی مشق منتخب کریں۔","مشکل نکتے سے شروع کریں یا Review کھولیں۔ کیلنڈر نئی محفوظ مشقیں دکھاتا ہے؛ پرانی مشقوں کی تاریخیں موجود نہیں ہو سکتیں۔"])],
 "lesson-notes":[tabs,step('.notes-main .tab-intro',["Notes with a way back.","These are AI notes from the transcript. Tap a time under a note to replay the teacher’s words; transcription errors can remain."],["ملاحظات مرتبطة بالشرح.","هذه ملاحظات آلية من النص. اضغط على الوقت لسماع كلام المعلّم؛ قد تبقى أخطاء في التفريغ."],["نوٹس سے اصل وضاحت تک۔","یہ متن سے بنے خودکار نوٹس ہیں۔ استاد کے الفاظ سننے کے لیے وقت پر دبائیں؛ متن میں غلطیاں رہ سکتی ہیں۔"])],
 "lesson-ask":[step('[data-tour="chat-scope"]',["Ask about this lesson.","Answers use this transcript only. Check the supporting audio. Religious interpretation belongs with a qualified teacher."],["اسأل عن هذا الدرس.","تستخدم الإجابات نص هذا الدرس فقط. استمع إلى المقطع الداعم. ارجع إلى معلّم مؤهّل للتفسير الديني."],["اسی سبق کے بارے میں پوچھیں۔","جوابات صرف اسی متن سے آتے ہیں۔ اصل آڈیو سنیں۔ دینی تشریح کے لیے مستند استاد سے رجوع کریں۔"])],
 "lesson-practice":[step('.practice-mode',["Try a question or turn a card.","Choose Quiz, Flashcards or a Lesson test. Tests reveal answers after submission. Saved responses set your next review."],["جرّب سؤالاً أو بطاقة.","اختر الأسئلة أو البطاقات. بعد المراجعة، استمع إلى المقطع الداعم. تحدّد إجابتك موعد المراجعة التالية."],["سوال یا کارڈ سے مشق کریں۔","Quiz یا Flashcards منتخب کریں۔ جواب دیکھنے کے بعد اصل حصہ سنیں۔ آپ کا جواب اگلی مشق کا وقت طے کرے گا۔"])],
 "lesson-transcript":[step('.transcript-workspace .search-field',["Find the teacher’s words.","Search this recording’s transcript and tap a timestamp to listen. Marked unclear passages need a careful replay."],["ابحث في كلام المعلّم.","ابحث في نص التسجيل واضغط على الوقت للاستماع. أعد سماع المقاطع المعلّمة بأنها غير واضحة بعناية."],["استاد کے الفاظ تلاش کریں۔","اس ریکارڈنگ کا متن تلاش کریں اور سننے کے لیے وقت پر دبائیں۔ غیر واضح نشان والے حصے احتیاط سے دوبارہ سنیں۔"])],
 "lesson-sources":[step('.sources-workspace .tab-intro',["Possible sources, separately.","Look up captured wording in the publisher’s records. A match does not confirm what the teacher intended, grade a narration or issue a ruling."],["مراجع محتملة في قسم منفصل.","ابحث عن الكلمات المسجّلة في سجلات الناشر. التطابق لا يؤكّد قصد المعلّم ولا يحكم على الحديث أو يصدر فتوى."],["ممکنہ حوالہ الگ دیکھیں۔","ریکارڈ شدہ الفاظ ناشر کے ریکارڈ میں تلاش کریں۔ مماثلت استاد کا مقصود ثابت نہیں کرتی، حدیث کی درجہ بندی یا فتویٰ نہیں دیتی۔"])]
};
const key=(userId:string,page:GuidePage)=>`darsloop-page-guide-${page==="plan"||page.startsWith("lesson-")?"v14":page==="library"||page==="classes"?"v13":page==="review"||page==="dictionary"?"v15":page==="insights"?"v12":"v7"}:${userId}:${page}`;
export function hasSeenPageGuide(userId:string,page:GuidePage):boolean{try{return localStorage.getItem(key(userId,page))==="seen";}catch{return false;}}
export function rememberPageGuide(userId:string,page:GuidePage){try{localStorage.setItem(key(userId,page),"seen");}catch{}}
