begin;
create temporary table darsloop_job_checks(name text,passed boolean);
grant select,insert on darsloop_job_checks to service_role;
insert into auth.users(id,email) values('10000000-0000-4000-8000-000000000011','darsloop-worker-check@example.invalid');
set local role service_role;
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare l jsonb:='{"id":"20000000-0000-4000-8000-000000000011","ownerId":"10000000-0000-4000-8000-000000000011","version":1,"status":"queued","segments":[]}';a record;b record;rejected boolean:=false;g uuid;r jsonb;
begin
 perform public.darsloop_queue(l,true);
 select * into a from public.darsloop_claim();
 insert into darsloop_job_checks values('queued job is atomically claimed',a.lesson_id=(l->>'id')::uuid and a.attempts=1);
 insert into darsloop_job_checks values('another claim cannot duplicate active job',not exists(select 1 from public.darsloop_claim()));
 update public.jobs set lease_until=now()-interval '1 second' where id=a.id;
 insert into darsloop_job_checks values('expired lease cannot renew',not public.darsloop_heartbeat(a.id,a.lease));
 select * into b from public.darsloop_claim();
 insert into darsloop_job_checks values('abandoned job gets a different fencing token',b.lease<>a.lease and b.attempts=2);
 begin perform public.darsloop_commit(a.id,a.lease,l,false);exception when others then rejected:=true;end;
 insert into darsloop_job_checks values('stale worker cannot commit',rejected);
 perform public.darsloop_commit(b.id,b.lease,jsonb_set(l,'{status}','"ready"'),true);
 insert into darsloop_job_checks select 'current worker completion is durable',status='done' from public.jobs where id=b.id;
 g:=public.darsloop_group((l->>'ownerId')::uuid,'Fictional worker class');
 insert into public.invites values('fictional-hash',g,now()+interval '24 hours',false);
 perform public.darsloop_join((l->>'ownerId')::uuid,'fictional-hash');rejected:=false;
 begin perform public.darsloop_join((l->>'ownerId')::uuid,'fictional-hash');exception when others then rejected:=true;end;
 insert into darsloop_job_checks values('invitation is consumed only once',rejected);
 insert into darsloop_job_checks values('first budget use succeeds',public.darsloop_budget((l->>'ownerId')::uuid,'fictional-budget',1));
 insert into darsloop_job_checks values('minute budget rejects excess',not public.darsloop_budget((l->>'ownerId')::uuid,'fictional-budget',1));
 r:=public.darsloop_review((l->>'ownerId')::uuid,(l->>'id')::uuid,'fictional-question',1,true);
 insert into darsloop_job_checks values('first recall schedules one day',(r->>'intervalDays')::int=1 and (r->>'attempts')::int=1);
 r:=public.darsloop_review((l->>'ownerId')::uuid,(l->>'id')::uuid,'fictional-question',1,true);
 insert into darsloop_job_checks values('second recall doubles private interval',(r->>'intervalDays')::int=2 and (r->>'attempts')::int=2);
 perform public.darsloop_vectors((l->>'id')::uuid,1,'fictional-embedding',2,'[{"hash":"fictional","vector":[1,0]}]','[]');
 rejected:=false;begin perform public.darsloop_vectors((l->>'id')::uuid,2,'fictional-embedding',2,'[]','[]');exception when others then rejected:=true;end;
 insert into darsloop_job_checks values('embedding write rejects stale version',rejected);
 delete from public.lessons where id=(l->>'id')::uuid;
 insert into darsloop_job_checks values('deletion cascades jobs reviews and vectors',not exists(select 1 from public.jobs where lesson_id=(l->>'id')::uuid) and not exists(select 1 from public.reviews where lesson_id=(l->>'id')::uuid) and not exists(select 1 from public.search_vectors where lesson_id=(l->>'id')::uuid));
end $$;
select name,passed from darsloop_job_checks;
rollback;
