import { themeScript } from "@/components/theme-control";
import type { Metadata } from "next";
import "@fontsource-variable/manrope";
import "@fontsource-variable/inter";
import "@fontsource-variable/bitter";
import "@fontsource-variable/bitter/wght-italic.css";
import "@fontsource-variable/lora";
import "@fontsource-variable/noto-sans-arabic";
import "./globals.css";
import "./premium.css";
import "./studio.css";
import "./editorial.css";
import "./product.css";
import "./upload.css";
import "./study-plan.css";
import "./home-shell.css";
import "./home-reference.css";
import "./upload-reference.css";
import "./insights-reference.css";
import "./review-reference.css";
import "./lessons-reference.css";
import "./classes-reference.css";
import "./plan-reference.css";
import "./lesson-reference.css";
import "./account-reference.css";
import "./recording-reference.css";
import "./learning-reference.css";
import "./theme.css";
import "./mobile-workspace.css";
import "./mobile-layout-refinements.css";
export const metadata:Metadata={title:"DarsLoop — AI notes and practice for Islamic classes",description:"Keep your class explanation close. Get notes, ask about your lesson, and practise with quizzes and flashcards. Built for students of Islamic knowledge."};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:themeScript}}/></head><body>{children}</body></html>;}
