"use client";
import { useState } from "react";
import { ArrowRight, BookOpen, Cards, Headphones } from "@phosphor-icons/react";
import { studyInsights, availablePractice } from "@/lib/insights";
import { type Lesson, type Review } from "@/lib/types";

function Activity({activity}:{activity:{day:string;attempts:number}[]}) {
  const today=new Date();today.setUTCHours(0,0,0,0);
  const cutoff=new Date(today);cutoff.setUTCDate(cutoff.getUTCDate()-83);
  const start=new Date(cutoff);start.setUTCDate(start.getUTCDate()-start.getUTCDay());
  const weekCount=Math.ceil((83+cutoff.getUTCDay()+1)/7);
  const days=Array.from({length:weekCount*7},(_,i)=>{const date=new Date(start);date.setUTCDate(date.getUTCDate()+i);return date;});
  const counts=new Map(activity.map(a=>[a.day,a.attempts]));
  return <figure className="insights-activity"><div className="activity-months" style={{gridTemplateColumns:`repeat(${weekCount},minmax(0,1fr))`}} aria-hidden="true">{Array.from({length:weekCount},(_,i)=>{const date=days[i*7];return <span key={i}>{i===0||date.getUTCMonth()!==days[(i-1)*7].getUTCMonth()?date.toLocaleDateString(undefined,{month:"short",timeZone:"UTC"}):""}</span>;})}</div><div className="activity-calendar"><div className="activity-weekdays" aria-hidden="true">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span key={d}>{d}</span>)}</div><div className="activity-cells" style={{gridTemplateColumns:`repeat(${weekCount},minmax(0,1fr))`}}>{days.map(date=>{const day=date.toISOString().slice(0,10),n=counts.get(day)||0,future=date>today||date<cutoff;return <span key={day} className={`activity-cell level-${n===0?0:n<3?1:n<6?2:3} ${future?"future-day":""}`} title={future?`${day}: outside the recorded activity window`:`${day}: ${n} recorded review ${n===1?"attempt":"attempts"}`} aria-label={future?`${day}: outside the recorded activity window`:`${day}: ${n} recorded review ${n===1?"attempt":"attempts"}`}/>;})}</div></div><figcaption><span>No recorded activity</span><span className="activity-key"><i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/></span><span>More attempts</span></figcaption></figure>;
}

export function Insights({lessons,reviews,onReview,onPractice}:{lessons:Lesson[];reviews:Review[];onReview:(lesson:Lesson,item:string)=>void;onPractice:()=>void}) {
  const [section,setSection]=useState<"progress"|"lessons">("progress");
  const data=studyInsights(lessons,reviews);
  const ready=lessons.filter(l=>!l.demo&&l.status==="ready"&&l.artifacts);
  return <section className="insights-reference">
    <header className="insights-heading"><div><h1>Insights</h1><p>A useful next step from your saved practice.</p></div><button className="insights-button" onClick={onPractice}><Cards size={17}/> Review</button></header>
    <nav className="insights-tabs" aria-label="Insights sections"><button aria-current={section==="progress"?"page":undefined} className={section==="progress"?"active":""} onClick={()=>setSection("progress")}>Your progress</button><button aria-current={section==="lessons"?"page":undefined} className={section==="lessons"?"active":""} onClick={()=>setSection("lessons")}>Your lessons</button></nav>
    <div className="insights-summary insights-compact-summary" data-tour="insights-summary">
      <article className="insights-metric"><strong>{data.due}</strong><h2>Due to review</h2><p>Questions and cards whose review time has arrived.</p></article>
      <article className="insights-metric"><strong>{data.untried}</strong><h2>Not tried yet</h2><p>Available practice you haven’t answered.</p></article>
      <article className="insights-metric"><strong>{data.missed}</strong><h2>Worth revisiting</h2><p>Latest quiz misses or cards marked forgotten.</p></article>
    </div>
    {section==="progress"?<>
      <article className="insights-data-card insights-actions" data-tour="insights-next"><header><div><h2>What to study next</h2><p>Due reviews first, then missed points and new practice.</p></div></header>{data.recommendations.length?<div className="insights-action-list">{data.recommendations.map(({lesson,item,reason})=><div className="insights-action-row" key={`${lesson.id}:${item.id}`}><div><span className="insights-reason" data-reason={reason}>{reason==="due"?"Due review":reason==="revisit"?"Try again":"First try"}</span><small dir="auto">{lesson.title} · {item.kind==="quiz"?"Quiz":"Flashcard"}</small><h3 dir="auto">{item.question}</h3></div><button className="insights-button" onClick={()=>onReview(lesson,item.id)}>Practise<ArrowRight size={16}/></button></div>)}</div>:<div className="insights-empty"><BookOpen size={25}/><p>{data.available?data.nextDueAt?`Your next saved review is ${new Date(data.nextDueAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}. You can revisit a lesson now.`:"You’ve tried the available practice. Return to a lesson whenever you need it.":"Prepare a lesson, then try its quiz or cards to see a next step here."}</p><button className="insights-button" onClick={onPractice}>Open Review<ArrowRight size={16}/></button></div>}</article>
      <div className="insights-detail-grid insights-learning-detail">
        <article className="insights-data-card"><header><h2>Your practice snapshot</h2><span>Current lesson versions</span></header><dl className="insights-snapshot"><div><dt>Practice items tried</dt><dd>{data.reviewed} / {data.available}</dd></div><div><dt>Latest quiz answers correct</dt><dd>{data.latestQuiz.correct} / {data.latestQuiz.total}</dd></div><div><dt>Cards marked remembered</dt><dd>{data.cards.remembered} / {data.cards.total}</dd></div><div><dt>Days practised in the last 7</dt><dd>{data.recentWeek.days} / 7</dd></div><div><dt>Saved attempts in the last 7 days</dt><dd>{data.recentWeek.attempts}</dd></div></dl><p className="insights-caption">Quiz answers and your own flashcard recall checks are separate. These counts describe practice, not mastery or school marks.</p></article>
        <article className="insights-data-card"><header><h2>Where to focus</h2><span>By course</span></header>{data.courses.some(c=>c.points>0)?<div className="insights-course-bars">{data.courses.filter(c=>c.points>0).map(c=><div className="insights-course-row" key={c.course}><div className="course-bar-title"><BookOpen size={18}/><strong dir="auto">{c.course}</strong><span>{c.reviewed} / {c.points} tried</span></div><div className="course-bar-track"><span style={{width:`${c.reviewed/c.points*100}%`}}/></div><p>{c.due} due · {c.points-c.reviewed} not tried · {c.missed} to revisit</p></div>)}</div>:<div className="insights-empty"><BookOpen size={25}/><p>Course coverage appears when supported practice is ready.</p></div>}<p className="insights-caption">Use these gaps to choose a lesson for your next review.</p></article>
      </div>
      <article className="insights-data-card activity-data-card insights-recorded-activity"><header><h2>Review activity</h2><span>Last 12 weeks · UTC</span></header><Activity activity={data.activity}/><p className="insights-caption">{data.trackedAttempts} dated review {data.trackedAttempts===1?"attempt":"attempts"}.{data.attempts>data.trackedAttempts?" Earlier attempts have no recorded dates.":" Activity appears when you save a review."}</p></article>
    </>:<article className="insights-data-card insights-lesson-table"><header><h2>Your lesson practice</h2><span>Current saved items</span></header>{ready.length?<div className="lesson-insight-rows">{ready.map(l=>{const items=availablePractice(l),counts=studyInsights([l],reviews),next=counts.recommendations[0]?.item||items[0];return <div key={l.id}><span className="lesson-insight-icon"><Headphones size={20}/></span><div><strong dir="auto">{l.title}</strong><small>{counts.reviewed} / {counts.available} tried · {counts.due} due · {counts.untried} new</small></div><button className="insights-button" disabled={!next} onClick={()=>next&&onReview(l,next.id)}>Practise<ArrowRight size={16}/></button></div>;})}</div>:<div className="insights-empty"><BookOpen size={25}/><p>Add a lesson to see its practice here.</p></div>}</article>}
    <footer className="insights-bottom-note">Uses your current lessons and saved responses. Sample lessons are excluded; dated activity uses UTC.</footer>
  </section>;
}
