"use client";
import { useState } from "react";
import { ArrowRight, BookOpen, Cards, CheckCircle, Headphones, ArrowCounterClockwise } from "@phosphor-icons/react";
import { studyInsights, availablePractice } from "@/lib/insights";
import { type Lesson, type Review } from "@/lib/types";

function Activity({activity}:{activity:{day:string;attempts:number}[]}) {
  const today=new Date();today.setUTCHours(0,0,0,0);
  const cutoff=new Date(today);cutoff.setUTCDate(cutoff.getUTCDate()-83);
  const start=new Date(cutoff);start.setUTCDate(start.getUTCDate()-start.getUTCDay());
  const weekCount=Math.ceil((83+cutoff.getUTCDay()+1)/7);
  const days=Array.from({length:weekCount*7},(_,i)=>{const date=new Date(start);date.setUTCDate(date.getUTCDate()+i);return date;});
  const counts=new Map(activity.map(a=>[a.day,a.attempts]));
  return <figure className="insights-activity"><div className="activity-months" style={{gridTemplateColumns:`repeat(${weekCount},minmax(0,1fr))`}} aria-hidden="true">{Array.from({length:weekCount},(_,i)=>{const date=days[i*7];return <span key={i}>{i===0||date.getUTCMonth()!==days[(i-1)*7].getUTCMonth()?date.toLocaleDateString(undefined,{month:"short",timeZone:"UTC"}):""}</span>;})}</div><div className="activity-calendar"><div className="activity-weekdays" aria-hidden="true">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span key={d}>{d}</span>)}</div><div className="activity-cells" style={{gridTemplateColumns:`repeat(${weekCount},minmax(0,1fr))`}}>{days.map(date=>{const day=date.toISOString().slice(0,10),n=counts.get(day)||0,future=date>today||date<cutoff;return <span key={day} className={`activity-cell level-${n===0?0:n<3?1:n<6?2:3} ${future?"future-day":""}`} title={future?`${day}: outside the recorded activity window`:`${day}: ${n} recorded review ${n===1?"attempt":"attempts"}`} aria-label={future?`${day}: outside the recorded activity window`:`${day}: ${n} recorded review ${n===1?"attempt":"attempts"}`}/>;})}</div></div><figcaption><span>No recorded activity</span><span className="activity-key"><i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/></span><span>More attempts</span></figcaption></figure>;
}

export function Insights({lessons,reviews,onReview,onPractice}:{lessons:Lesson[];reviews:Review[];onReview:(lesson:Lesson,item:string)=>void;onPractice:()=>void}) {
  const [section,setSection]=useState<"progress"|"lessons">("progress");
  const data=studyInsights(lessons,reviews),coverage=data.available?Math.round(data.reviewed/data.available*100):0;
  const ready=lessons.filter(l=>!l.demo&&l.status==="ready"&&l.artifacts),firstMiss=data.revisits[0];
  return <section className="insights-reference">
    <header className="insights-heading"><div><h1>Insights</h1><p>Your practice, and what to try next.</p></div><button className="insights-button" onClick={onPractice}><Cards size={17}/> Start a review</button></header>
    <nav className="insights-tabs" aria-label="Insights sections"><button aria-current={section==="progress"?"page":undefined} className={section==="progress"?"active":""} onClick={()=>setSection("progress")}>Your progress</button><button aria-current={section==="lessons"?"page":undefined} className={section==="lessons"?"active":""} onClick={()=>setSection("lessons")}>Your lessons</button></nav>
    <div className="insights-summary" data-tour="insights-summary">
      <article className="insights-metric coverage-metric"><strong>{data.reviewed}<small> / {data.available}</small></strong><h2>Practice items tried</h2><div className="coverage-gauge"><svg viewBox="0 0 180 104" role="img" aria-label={`${coverage}% of available practice tried`}><path d="M 16 88 A 74 74 0 0 1 164 88" pathLength="100"/>{coverage>0&&<path className="gauge-value" d="M 16 88 A 74 74 0 0 1 164 88" pathLength="100" strokeDasharray={`${coverage} 100`}/>}</svg><div><span>Of your practice</span><b>{coverage}%</b></div></div></article>
      <article className="insights-metric results-metric"><strong>{data.latestQuiz.correct}<small> / {data.latestQuiz.total}</small></strong><h2>Latest quiz answers correct</h2><div className="metric-divider"/><p><CheckCircle size={18}/><b>{data.latestQuiz.correct}</b> correct</p><p><ArrowCounterClockwise size={18}/><b>{data.latestQuiz.total-data.latestQuiz.correct}</b> to try again</p><small className="metric-footnote">Flashcards: {data.cards.remembered} / {data.cards.total} remembered.<br/>Based on your own recall check.</small></article>
      <article className="insights-metric next-metric" data-tour="insights-next"><strong>{data.due}</strong><h2>Ready to review</h2><div className="metric-divider"/><div className="next-review-copy"><span className="next-review-icon"><Headphones size={25}/></span><div><h3>{firstMiss?"Try a missed point again":data.due?"Your next review is ready":"Keep your lesson fresh"}</h3><p>{firstMiss?firstMiss.lesson.title:data.due?"Return to the questions and cards you’ve tried.":data.nextDueAt?`Next review: ${new Date(data.nextDueAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}`:"Choose a lesson and try a short drill."}</p></div></div><button className="insights-button" onClick={()=>firstMiss?onReview(firstMiss.lesson,firstMiss.item.id):onPractice()}>{firstMiss?"Hear it again & try":"Open Review"}<ArrowRight size={17}/></button></article>
    </div>
    {section==="progress"?<div className="insights-detail-grid">
      <article className="insights-data-card"><header><h2>Your courses</h2><span>{data.readyLessons} ready {data.readyLessons===1?"lesson":"lessons"}</span></header>{data.courses.length?<div className="insights-course-bars">{data.courses.map(c=><div className="insights-course-row" key={c.course}><div className="course-bar-title"><BookOpen size={20}/><strong dir="auto">{c.course}</strong><span>{c.reviewed} / {c.points} tried</span></div><div className="course-bar-track"><span style={{width:`${c.points?c.reviewed/c.points*100:0}%`}}/></div><p>{c.correctQuiz} / {c.triedQuiz} latest quiz answers correct{c.due>0&&<> · {c.due} due</>}</p></div>)}</div>:<div className="insights-empty"><BookOpen size={28}/><p>Your courses will appear after a lesson is ready.</p></div>}<p className="insights-caption">Bars show practice tried in each course.</p></article>
      <article className="insights-data-card activity-data-card"><header><h2>Review activity</h2><span>Last 12 weeks · UTC</span></header><Activity activity={data.activity}/><p className="insights-caption">{data.trackedAttempts} dated review {data.trackedAttempts===1?"attempt":"attempts"}.{data.attempts>data.trackedAttempts?" Earlier attempts have no recorded dates.":" Activity appears when you save a review."}</p></article>
    </div>:<article className="insights-data-card insights-lesson-table"><header><h2>Your lesson practice</h2><span>Current lesson versions</span></header>{ready.length?<div className="lesson-insight-rows">{ready.map(l=>{const items=availablePractice(l),counts=studyInsights([l],reviews);return <div key={l.id}><span className="lesson-insight-icon"><Headphones size={23}/></span><div><strong dir="auto">{l.title}</strong><small>{l.course} · {counts.reviewed} / {counts.available} practice tried</small></div><button className="insights-button" disabled={!items.length} onClick={()=>items[0]&&onReview(l,items[0].id)}>Practise<ArrowRight size={16}/></button></div>;})}</div>:<div className="insights-empty"><BookOpen size={28}/><p>Add a lesson to see its practice here.</p></div>}</article>}
    {data.revisits.length>0&&<article className="insights-data-card insights-missed"><header><h2>Worth another look</h2><span>Your latest missed responses</span></header>{data.revisits.slice(0,3).map(({lesson,item})=><div className="insights-missed-row" key={`${lesson.id}:${item.id}`}><span className="missed-replay-icon"><ArrowCounterClockwise size={21}/></span><div><small>{lesson.course} · {item.kind==="quiz"?"Quiz":"Flashcard"}</small><h3 dir="auto">{item.question}</h3></div><button className="insights-button" onClick={()=>onReview(lesson,item.id)}>Review<ArrowRight size={16}/></button></div>)}</article>}
    <footer className="insights-bottom-note">Counts use your saved practice and current lessons. Quiz results show your latest answer to each question. Ask your teacher about school marks or religious guidance.</footer>
  </section>;
}
