"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, AudioLines, BookOpen, Check, Headphones, Layers, MessageCircle, Pause, Play, RotateCcw } from "lucide-react";
import { formatTime, type Lesson } from "@/lib/types";

export function LessonScene(){
  const [reduced,setReduced]=useState(true),[playing,setPlaying]=useState(false),[run,setRun]=useState(0);
  useEffect(()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>{setReduced(media.matches);setPlaying(!media.matches);};update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update);},[]);
  useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>setPlaying(false),4800);return()=>clearTimeout(timer);},[playing,run]);
  return <div className={`dl-scene ${playing&&!reduced?"dl-scene-running":""}`}>
    <div className="dl-scene-light" aria-hidden="true"/><div className="dl-scene-plinth" aria-hidden="true"/>
    <div className="dl-scene-image" key={`image-${run}`}><Image src="/art/study-desk-v3.webp" alt="A green notebook, headphones and an audio recorder" width={1100} height={825} priority unoptimized sizes="(max-width: 760px) 100vw, 50vw"/></div>
    <div className="dl-scene-card" key={`card-${run}`}><span className="dl-scene-card-icon"><AudioLines size={21}/></span><div><strong>One lesson. More ways to learn.</strong><div className="dl-scene-route"><span>Record</span><ArrowRight size={12}/><span>AI notes</span><ArrowRight size={12}/><span>Revision</span></div></div><span className="dl-scene-wave" aria-hidden="true">{[14,26,18,33,22,30,15].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*70}ms`}}/>)}</span></div>
    <div className="dl-scene-caption"><span>Original study illustration</span><button aria-label={playing?"Pause illustration":"Replay illustration"} disabled={reduced} onClick={()=>{if(playing)setPlaying(false);else{setRun(r=>r+1);setPlaying(true);}}}>{playing?<Pause size={13}/>:<RotateCcw size={13}/>} {playing?"Pause":"Replay"}</button></div>
  </div>;
}

export function LandingPreview({lesson}:{lesson:Lesson}){
  const [tab,setTab]=useState(0),[choice,setChoice]=useState<string|null>(null),[checked,setChecked]=useState(false),[listening,setListening]=useState(false),[audioError,setAudioError]=useState("");
  const audio=useRef<HTMLAudioElement>(null),pending=useRef<number|null>(null);
  const note=lesson.artifacts!.notes[0],question=lesson.artifacts!.practice.find(p=>p.kind==="quiz")!,segment=lesson.segments.find(s=>s.id===note.evidence[0].segmentId)!;
  async function play(){const a=audio.current;if(!a)return;setAudioError("");if(!a.paused){a.pause();return;}pending.current=segment.start;try{if(a.readyState<1)a.load();else{a.currentTime=segment.start;pending.current=null;await a.play();}}catch{setAudioError("Open the example lesson to hear this passage.");}}
  const labels=["Notes","Ask this class","Quiz"],icons=[BookOpen,MessageCircle,Layers];
  return <div className="dl-preview">
    <div className="dl-preview-sidebar"><div className="dl-preview-book"><BookOpen size={24}/></div><strong>Adab of learning</strong><span>Fictional sample lesson</span><div className="dl-preview-tabs" role="tablist" aria-label="Explore a sample lesson">{labels.map((name,i)=>{const Icon=icons[i];return <button key={name} role="tab" id={`preview-tab-${i}`} aria-selected={tab===i} aria-controls="preview-panel" tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{if(["ArrowRight","ArrowLeft","ArrowDown","ArrowUp","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?0:e.key==="End"?2:(i+(["ArrowRight","ArrowDown"].includes(e.key)?1:2))%3;setTab(next);document.getElementById(`preview-tab-${next}`)?.focus();}}}><Icon size={17}/>{name}<ArrowRight size={15}/></button>;})}</div><Link href="/example">Open the full example <ArrowRight size={15}/></Link></div>
    <div id="preview-panel" className="dl-preview-panel" role="tabpanel" aria-labelledby={`preview-tab-${tab}`}>
      <div className="dl-preview-top"><span className="mini-label">PREPARED SAMPLE · NO LIVE AI REQUEST</span><span><Headphones size={14}/> {formatTime(lesson.duration)} audio</span></div>
      {tab===0?<div className="dl-preview-content"><span className="dl-preview-overline">CLASS NOTES</span><h3>{note.heading}</h3><p>{note.text}</p><blockquote>“First follow the explanation. Afterwards, use the recording to fill in the points you missed.”</blockquote><button className="dl-audio-pill" onClick={()=>void play()}>{listening?<Pause size={14}/>:<Play size={14} fill="currentColor"/>}{formatTime(segment.start)} <span>{listening?"Pause the passage":"Hear the teacher’s words"}</span></button></div>:tab===1?<div className="dl-preview-content"><div className="dl-preview-question"><MessageCircle size={18}/><p>What should I do while the teacher is speaking?</p></div><span className="dl-preview-overline">PASSAGE FROM THIS CLASS</span><blockquote>“{segment.text}”</blockquote><button className="dl-audio-pill" onClick={()=>void play()}>{listening?<Pause size={14}/>:<Play size={14} fill="currentColor"/>}{formatTime(segment.start)} <span>Play the supporting passage</span></button><p className="dl-preview-small">This preview shows a prepared passage. In your own lesson, use the chatbot to ask a question.</p></div>:<div className="dl-preview-content"><span className="dl-preview-overline">TRY A QUESTION</span><h3>{question.question}</h3><div className="dl-preview-choices">{question.choices.map((c,i)=><button key={c} aria-pressed={choice===c} disabled={checked} onClick={()=>setChoice(c)} className={`${choice===c?"chosen":""} ${checked&&c===question.answer?"correct-choice":""}`}><span>{String.fromCharCode(65+i)}</span>{c}{checked&&c===question.answer&&<Check size={17}/>}</button>)}</div>{checked?<div className="dl-preview-result" role="status"><strong>{choice===question.answer?"That matches the lesson.":"Here’s the point to revisit."}</strong><p>{question.answer}</p><button className="dl-audio-pill" onClick={()=>void play()}><Headphones size={14}/>{formatTime(segment.start)} Hear the explanation</button><button className="text-link" onClick={()=>{setChecked(false);setChoice(null);}}>Try again</button></div>:<button className="button primary small" disabled={!choice} onClick={()=>setChecked(true)}>Check answer <ArrowRight size={16}/></button>}</div>}
      <p className="dl-preview-note">{audioError||"Prepared from a fictional script. Your own uploads use the connected AI services."}</p>
      <audio ref={audio} src="/example/audio" preload="none" onPlay={()=>setListening(true)} onPause={()=>setListening(false)} onEnded={()=>setListening(false)} onTimeUpdate={()=>{const a=audio.current;if(a&&a.currentTime>=segment.end&&!a.paused)a.pause();}} onError={()=>setAudioError("Open the example lesson to hear this passage.")} onLoadedMetadata={()=>{const a=audio.current;if(a&&pending.current!==null){a.currentTime=pending.current;pending.current=null;void a.play().catch(()=>setAudioError("Press play to hear the passage."));}}}/>
    </div>
  </div>;
}
