"use client";
import { useEffect, useId, useRef, useState } from 'react';
import { ArrowRight, BookOpen, CalendarBlank, Check, Headphones, MagnifyingGlass, Play, DownloadSimple, Question, WarningCircle } from '@phosphor-icons/react';
import { catchUpPoints, citationStart, examWeek, localDay, teacherTerms } from '@/lib/learning-tools';
import { formatTime, type Lesson, type Review } from '@/lib/types';
import { SourceEvidence, SourceLink } from "./source-evidence";
import { sourceLabel, citedPassage, pdfSourceUrl } from "@/lib/source-passages";
import { Modal } from './modal';
import { exclusiveAudio, playAt } from '@/lib/audio-playback';
import examStyles from './exam-week.module.css';

function AudioCatchUp({lesson,onPlay}:{lesson:Lesson;onPlay:(time:number)=>void}){
  const points=catchUpPoints(lesson),moments=points.slice(0,3);
  const [clip,setClip]=useState<{start:number;end:number}|null>(null),[error,setError]=useState('');
  const audio=useRef<HTMLAudioElement>(null);
  async function listen(start:number,end:number){setError('');setClip({start,end:Math.min(lesson.duration,Math.max(start+30,end))});const a=audio.current;if(!a)return;try{await playAt(a,start);}catch{setError('The audio could not play. Open the original recording below.');}}
  return <div className="catch-up-page"><header className="learning-tool-heading"><span className="learning-tool-kicker">CATCH ME UP</span><h2>Pick up where the class left off.</h2><p>{points.length?`${points.length} supported ${points.length===1?'point':'points'} from this lesson. Listen to the words behind each one.`:'No clear notes for a briefing yet. Use the transcript and original audio.'}</p></header>
    <audio ref={audio} preload="metadata" src={lesson.demo?'/example/audio':`/api/lessons/${lesson.id}/audio?v=${lesson.version}`} onPlay={e=>exclusiveAudio(e.currentTarget)} onTimeUpdate={()=>{if(clip&&audio.current&&audio.current.currentTime>=clip.end)audio.current.pause();}} onError={()=>setError('The audio is unavailable. Try the original recording below.')} />
    {error&&<p role="alert">{error}</p>}
    <div className="catch-up-layout"><ol className="catch-up-points">{points.map((point,index)=>{const start=citationStart(lesson,point.evidence),end=lesson.segments.find(s=>s.id===point.evidence[0]?.segmentId)?.end??start+30;return <li key={index}><span className="catch-up-number">{index+1}</span><article><h3 dir="auto">{point.heading}</h3><p dir="auto">{point.text}</p><div className="catch-up-point-actions"><button onClick={()=>void listen(start,end)}><Play size={14} weight="fill"/>Listen to this moment <bdi>{formatTime(start)}</bdi></button><details><summary>Teacher’s words</summary>{point.evidence.map((c,i)=><blockquote dir="auto" key={i}>{c.quote}</blockquote>)}</details></div></article></li>;})}</ol><aside className="catch-up-moments"><Headphones size={28}/><h3>Hear the full context</h3><p>A briefing is a starting point. These are the first supported topics, not an importance ranking.</p>{moments.map((point,index)=><button key={index} onClick={()=>{audio.current?.pause();onPlay(citationStart(lesson,point.evidence));}}><span dir="auto">{point.heading}</span><ArrowRight size={16}/></button>)}<small>AI notes can miss details. Check important wording with your teacher.</small></aside></div>
  </div>;
}

export function TeacherDictionary({lessons,onOpen,onPlay}:{lessons:Lesson[];onOpen:(lesson:Lesson)=>void;onPlay:(lesson:Lesson,time:number)=>void}){
  const [query,setQuery]=useState(''),[course,setCourse]=useState('');
  const entries=teacherTerms(lessons,course,query),courses=[...new Set(lessons.map(l=>l.course))].sort();
  return <section className="teacher-dictionary learning-reference-page"><header className="learning-tool-heading"><span className="learning-tool-kicker">FROM YOUR CLASSES</span><h1>Teacher’s terms</h1><p>Explanations captured in your lessons and PDF sources, with their original passages.</p></header><div className="dictionary-controls" data-tour="dictionary-search"><label><MagnifyingGlass size={18}/><input aria-label="Search teacher terms" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a term or explanation…"/></label><select aria-label="Term course" value={course} onChange={e=>setCourse(e.target.value)}><option value="">All courses</option>{courses.map(c=><option key={c}>{c}</option>)}</select></div><p className="dictionary-scope">Spellings and definitions are extracted or transcribed and AI-organised. Check their original source. Different lessons stay separate; this is not an outside dictionary.</p><div className="dictionary-entries" data-tour="dictionary-entries">{entries.length?entries.map(entry=><article key={entry.id}><div className="dictionary-entry-header"><BookOpen size={21}/><h2 dir="auto">{entry.term}</h2><bdi>{sourceLabel(citedPassage(entry.lesson,entry.evidence[0]))}</bdi></div><p dir="auto">{entry.definition}</p><details><summary>{entry.lesson.sourceKind==="pdf"?"Source excerpt":"Teacher’s captured words"}</summary>{entry.evidence.map((c,i)=><blockquote dir="auto" key={i}>{c.quote}</blockquote>)}</details><footer><button onClick={()=>onOpen(entry.lesson)} dir="auto">{entry.lesson.title}</button><SourceLink lesson={entry.lesson} citation={entry.evidence[0]} onPlay={time=>onPlay(entry.lesson,time)}/></footer></article>):<div className="learning-empty"><BookOpen size={32}/><h2>{query?'No matching term':'Your class terms will appear here'}</h2><p>{query?'Try a word from the explanation or another course.':'Only clearly supported definitions enter this collection. Nothing is filled in from outside your lesson.'}</p></div>}</div></section>;
}

export function ExamWeek({userId,lessons,reviews,onOpen,onPractice}:{userId:string;lessons:Lesson[];reviews:Review[];onOpen:(lesson:Lesson)=>void;onPractice:(lesson:Lesson,id:string)=>void}){
  const [date,setDate]=useState(''),[course,setCourse]=useState(''),[saved,setSaved]=useState(false),[storageError,setStorageError]=useState(false);
  const controlsId=useId();
  useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(`darsloop-exam:${userId}`)||'null');if(raw&&typeof raw.date==='string'&&typeof raw.course==='string'){setDate(raw.date);setCourse(raw.course);setSaved(true);}}catch{}},[userId]);
  const courses=[...new Set(lessons.filter(l=>l.status==='ready'&&!l.demo).map(l=>l.course))];
  const days=examWeek(lessons,reviews,date,course),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);
  function save(){try{localStorage.setItem(`darsloop-exam:${userId}`,JSON.stringify({date,course}));setStorageError(false);setSaved(true);}catch{setStorageError(true);}}
  function reset(){setDate('');setCourse('');setSaved(false);try{localStorage.removeItem(`darsloop-exam:${userId}`);}catch{setStorageError(true);}}
  return <section className="exam-week"><header><CalendarBlank size={22}/><div><h2>Exam week</h2><p>A short schedule for the seven days before your date.</p></div></header><div className={examStyles.controls}><div className={examStyles.field}><label htmlFor={`${controlsId}-date`}>Exam date</label><input id={`${controlsId}-date`} type="date" min={localDay(tomorrow)} value={date} onChange={e=>{setDate(e.target.value);setSaved(false);}}/></div><div className={examStyles.field}><label htmlFor={`${controlsId}-course`}>Course</label><select id={`${controlsId}-course`} value={course} onChange={e=>{setCourse(e.target.value);setSaved(false);}}><option value="">All courses</option>{courses.map(c=><option key={c}>{c}</option>)}</select></div><div className={examStyles.actions}><button className={examStyles.save} disabled={!days.length} onClick={save}>{saved?<><Check size={15}/>Saved here</>:<>Save schedule<ArrowRight size={15}/></>}</button>{date&&<button className={examStyles.reset} onClick={reset}>Clear</button>}</div></div>{storageError&&<p role="alert">The schedule could not be saved on this device. You can still use the dates below.</p>}
    {!!days.length&&<><p className="exam-week-scope">Missed quiz points come first, then due and untried topics. This uses your available lessons, not a complete exam syllabus. The date is saved on this device; topic order updates with your responses.</p><div className="exam-week-days">{days.map(day=><details key={day.date} open={day===days[0]}><summary><bdi>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</bdi><span>{day.topics.length} {day.topics.length===1?'topic':'topics'}</span></summary>{day.topics.length?day.topics.map(topic=>{const lesson=lessons.find(l=>l.id===topic.lessonId)!;return <button key={topic.id} onClick={()=>topic.practiceItemIds[0]?onPractice(lesson,topic.practiceItemIds[0]):onOpen(lesson)}><span dir="auto">{topic.title}<small>{lesson.title} · {sourceLabel(topic.sources[0])}</small></span><ArrowRight size={15}/></button>;}):<p>No new topics assigned. Revisit your notes if useful.</p>}</details>)}</div></>}
  </section>;
}

/** A listening-first question handoff. No approval status, scholarly credential or certainty claim. */
function AudioTeacherCheck({lesson,onClose}:{lesson:Lesson;onClose:()=>void}){
  const passages=lesson.segments.filter(s=>s.flags.length),[id,setId]=useState(passages[0]?.id||lesson.segments[0]?.id||''),[question,setQuestion]=useState(''),[listened,setListened]=useState(false),[error,setError]=useState('');
  const segment=lesson.segments.find(s=>s.id===id),audio=useRef<HTMLAudioElement>(null),clock=useRef<{wall:number;media:number}|null>(null),heard=useRef(0);
  useEffect(()=>{setListened(false);setQuestion('');heard.current=0;clock.current=null;},[id]);
  async function start(){if(!audio.current||!segment)return;setError('');try{await playAt(audio.current,segment.start);}catch{setError('Audio could not play. Try again before preparing a question.');}}
  function track(){const a=audio.current;if(!a||!segment)return;const current={wall:performance.now(),media:a.currentTime},old=clock.current;clock.current=current;if(!a.paused&&old&&a.currentTime>=segment.start&&a.currentTime<=segment.end+.5){const delta=current.media-old.media,wall=(current.wall-old.wall)/1000;if(delta>0&&delta<=wall*a.playbackRate+1&&wall<2)heard.current+=Math.min(delta,wall*a.playbackRate);if(heard.current>=Math.min(3,Math.max(.5,segment.end-segment.start-.2)))setListened(true);}if(a.currentTime>=segment.end)a.pause();}
  function download(){if(!listened||!segment||!question.trim())return;const text=`Question for my teacher\nLesson: ${lesson.title}\nPassage: ${formatTime(segment.start)} – ${formatTime(segment.end)} · transcript v${lesson.version}\n\nCaptured words (may be wrong):\n${segment.text}\n${segment.flags.join('; ')}\n\nMy question:\n${question.trim()}\n\nThis is a question handoff, not approval or authentication. Listen to the original audio together.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='DarsLoop-question-for-teacher.txt';a.click();URL.revokeObjectURL(url);}
  return <Modal title="Question for my teacher" className="teacher-check-modal" onClose={onClose}><p>Replay one passage, then prepare a question to take to your teacher. Nothing here is marked correct.</p><label className="field">Passage<select value={id} onChange={e=>setId(e.target.value)}>{lesson.segments.map(s=><option key={s.id} value={s.id}>{formatTime(s.start)} · {s.flags.length?'Unclear · ':''}{s.text.length>60?`${s.text.slice(0,60).replace(/\s+\S*$/u, "")}…`:s.text}</option>)}</select></label>{segment&&<><div className="teacher-check-quote"><span>{segment.flags.length?<><WarningCircle size={15}/>Unclear wording</>:<>Captured transcript · check the audio</>}</span><blockquote dir="auto">{segment.text}</blockquote><button onClick={()=>void start()}><Play size={14} weight="fill"/>Replay this passage <bdi>{formatTime(segment.start)}</bdi></button></div><audio ref={audio} controls preload="metadata" src={lesson.demo?'/example/audio':`/api/lessons/${lesson.id}/audio?v=${lesson.version}`} onPlay={e=>exclusiveAudio(e.currentTarget)} onTimeUpdate={track} onSeeking={()=>{clock.current=null;}} onPause={()=>{clock.current=null;}} onError={()=>setError('The original audio is unavailable.')}/><label className="field">Your question<textarea rows={3} maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What wording or explanation should I check?"/></label><p className="teacher-check-status">{listened?<><Check size={15}/>Passage replayed. You can prepare your question.</>:<><Headphones size={15}/>Listen to a few seconds before downloading your question.</>}</p><button className="learning-primary" disabled={!listened||!question.trim()} onClick={download}><DownloadSimple size={17}/>Download question</button>{error&&<p role="alert">{error}</p>}</>}<small>This does not mark the transcript as correct. Your teacher’s response happens outside the app.</small></Modal>;
}

export function CatchUp(props:{lesson:Lesson;onPlay:(time:number)=>void}){
  if(props.lesson.sourceKind!=="pdf")return <AudioCatchUp {...props}/>;
  const points=catchUpPoints(props.lesson);
  return <div className="catch-up-page"><header className="learning-tool-heading"><span className="learning-tool-kicker">CATCH ME UP</span><h2>Pick up from this source.</h2><p>First supported topics from this PDF; check each cited page for full context.</p></header><ol className="catch-up-points">{points.map((point,index)=><li key={index}><span className="catch-up-number">{index+1}</span><article><h3 dir="auto">{point.heading}</h3><p dir="auto">{point.text}</p><SourceEvidence evidence={point.evidence} {...props}/></article></li>)}</ol>{!points.length&&<p>No supported briefing yet. Open PDF pages to read the source.</p>}</div>;
}
export function TeacherCheck(props:{lesson:Lesson;onClose:()=>void}){return props.lesson.sourceKind==="pdf"?<PdfTeacherCheck {...props}/>:<AudioTeacherCheck {...props}/>;}
function PdfTeacherCheck({lesson,onClose}:{lesson:Lesson;onClose:()=>void}){
  const [id,setId]=useState(lesson.pdfPages?.[0]?.id??""),[question,setQuestion]=useState(""),[checked,setChecked]=useState(false);
  const page=lesson.pdfPages?.find(p=>p.id===id);
  function download(){if(!page||!checked||!question.trim())return;const text=`Question for my teacher\nSource: ${lesson.title}\nPDF page ${page.page} · source v${lesson.version}\n\nExtracted source text (check original layout):\n${page.text}\n\nMy question:\n${question.trim()}\n\nThis is a question handoff, not approval or authentication. Read the original PDF together.`;const url=URL.createObjectURL(new Blob([text],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download="DarsLoop-question-for-teacher.txt";a.click();URL.revokeObjectURL(url);}
  return <Modal title="Question for my teacher" className="teacher-check-modal" onClose={onClose}><p>Check the original PDF page, then prepare a question to take to your teacher. Nothing here is marked correct.</p><label className="field">PDF page<select value={id} onChange={e=>{setId(e.target.value);setChecked(false);}}>{lesson.pdfPages?.map(p=><option key={p.id} value={p.id}>Page {p.page}</option>)}</select></label>{page&&<><div className="teacher-check-quote"><span>Source excerpt · check the PDF</span><blockquote dir="auto">{page.text}</blockquote><a className="timestamp" href={pdfSourceUrl(lesson,page.page)} target="_blank" rel="noreferrer">Open page {page.page}</a></div><label className="check-row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I checked the original PDF page.</label><label className="field">Your question<textarea rows={3} maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)}/></label><button className="learning-primary" disabled={!checked||!question.trim()} onClick={download}><DownloadSimple size={17}/>Download question</button></>}<small>This does not mark the source or interpretation as correct. Your teacher’s response happens outside the app.</small></Modal>;
}
