"use client";
import { useEffect, useRef, useState } from "react";
import { DownloadSimple as ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUp, ArrowCounterClockwise, BookOpen, Check, CaretDown as ChevronDown, ArrowSquareOut as ExternalLink, Headphones, Cards as Layers, CircleNotch as LoaderCircle, ChatCircle as MessageCircle, Play, MagnifyingGlass as Search, ShieldCheck, Trash as Trash2, Users, X, ClipboardText, CheckCircle, FileAudio, WarningCircle } from "@phosphor-icons/react";
import { formatTime, type Answer, type Candidate, type Citation, type Lesson, type PracticeItem, type Review } from "@/lib/types";
import { StudyAvatar } from "./study-avatar";
import { api, message } from "./client-api";
import { excerptAnswer } from "@/lib/evidence";
import { exampleReview } from "@/lib/example-practice";
import Link from "next/link";
import { availablePractice } from "@/lib/insights";
import { CatchUp, TeacherCheck } from "./learning-tools";
import { PracticeSession } from "./practice-session";

export type LessonTab="notes"|"ask"|"practice"|"transcript"|"sources"|"catchup";
export function Evidence({evidence,lesson,onPlay}:{evidence:Citation[];lesson:Lesson;onPlay:(time:number)=>void}) {
  return <div className="evidence-row">{evidence.map((c,i)=>{const s=lesson.segments.find(s=>s.id===c.segmentId);return s?<div className="evidence-link" key={c.segmentId+String(i)}><button className="timestamp" onClick={()=>onPlay(s.start)} aria-label={`Play passage at ${formatTime(s.start)}`}><Play size={11} weight="fill"/><bdi>{formatTime(s.start)}</bdi></button><details className="quote-detail"><summary>Teacher’s words <ChevronDown size={13}/></summary><blockquote dir="auto">{c.quote}</blockquote></details></div>:null;})}</div>;
}
export function Notes({lesson,onPlay}:{lesson:Lesson;onPlay:(time:number)=>void}) {
  const a=lesson.artifacts;if(lesson.noteOptions?.enabled===false&&a)return <div className="notes-main"><div className="tab-intro"><h2>Notes are turned off.</h2><p>You chose to skip notes for this lesson. Your transcript, class questions and practice are available in the tabs above.</p></div></div>;if(!a)return <div className="notes-main"><div className="tab-intro"><h2>Your class notes.</h2><p>Your transcript and recording are available in the tabs above.</p></div><div className="empty-state"><BookOpen/><h3>{lesson.error?"Notes couldn’t be prepared.":"Notes are still being prepared."}</h3><p>Your original recording is available below.</p></div></div>;
  return <div className="notes-layout"><div className="notes-main"><div className="tab-intro"><p className="eyebrow">{lesson.demo?"PREPARED EXAMPLE NOTES":"AI NOTES · FROM THIS LESSON"}</p><h2>Your class notes.</h2><p>{lesson.demo?"This fictional lesson comes with prepared notes. Fresh uploads use the connected AI services.":"Automatically organized from clear transcript passages. Use the audio to check the explanation."}</p></div>{a.overview&&<details className="lesson-summary"><summary><span>Short summary <small>· {lesson.demo?"prepared example":"AI from your lesson"}</small></span><ChevronDown size={16}/></summary><p dir="auto">{a.overview}</p><Evidence evidence={a.notes.slice(0,3).flatMap(note=>note.evidence).filter((citation,index,list)=>list.findIndex(other=>other.segmentId===citation.segmentId)===index)} lesson={lesson} onPlay={onPlay}/></details>}{a.notes.map((n,i)=><article className="note-section" key={i}><div className="note-number">{String(i+1).padStart(2,"0")}</div><div><h3 dir="auto">{n.heading}</h3><p dir="auto">{n.text}</p><Evidence evidence={n.evidence} lesson={lesson} onPlay={onPlay}/></div></article>)}</div><aside className="lesson-aside"><div className="term-panel"><span className="mini-label"><BookOpen size={15}/> TERMS FROM THE LESSON</span><h3>Terms explained in class.</h3>{!lesson.demo&&<p className="muted">Term spellings are as transcribed. Replay the audio to check them.</p>}{a.terms.length?a.terms.map((t,i)=><div className="term" key={i}><strong dir="auto">{t.term}</strong><p dir="auto">{t.definition}</p><Evidence evidence={t.evidence} lesson={lesson} onPlay={onPlay}/></div>):<p className="muted">No clear term definitions were captured. Definitions won’t be filled in from outside this lesson.</p>}</div><div className="aside-tip"><Headphones size={20}/><h3>Tap a time to listen.</h3><p>A note is a way back to the explanation. Tap its time to listen to the original passage.</p></div></aside></div>;
}
export function Chat({lesson,onPlay,onError,configured,preview=false,home=false,tools,actions,composerActions,emptyState,draft}:{lesson:Lesson;onPlay:(time:number)=>void;onError:(s:string)=>void;configured:boolean;preview?:boolean;home?:boolean;tools?:React.ReactNode;actions?:React.ReactNode;composerActions?:React.ReactNode;emptyState?:React.ReactNode;draft?:{text:string;nonce:number;submit?:boolean}}) {
  const [question,setQuestion]=useState(""),[turns,setTurns]=useState<{question:string;answer?:Answer}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");const bottom=useRef<HTMLDivElement>(null),controller=useRef<AbortController|null>(null),sentDraft=useRef<number|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  useEffect(()=>{
    if(!draft)return;
    setQuestion(draft.text);requestAnimationFrame(()=>document.getElementById("class-question")?.focus());
    if(!draft.submit)return;
    // Defer until the lesson is mounted; cleanup prevents duplicate sends on
    // remount. Only a question explicitly submitted/selected by the user runs.
    const timer=setTimeout(()=>{if(sentDraft.current!==draft.nonce){sentDraft.current=draft.nonce;void ask(draft.text);}},0);
    return ()=>clearTimeout(timer);
  },[draft]);
  useEffect(()=>{if(turns.length)bottom.current?.scrollIntoView({behavior:"auto",block:"nearest"});},[turns,busy]);
  async function ask(text:string){if(busy||text.trim().length<2)return;const q=text.trim();setQuestion("");setError("");setBusy(true);setTurns(t=>[...t,{question:q}]);controller.current=new AbortController();try{
    const answer=preview?excerptAnswer(q,lesson.segments,lesson.version):await api<Answer>(`/api/lessons/${lesson.id}/chat`,{method:"POST",body:JSON.stringify({question:q,version:lesson.version}),signal:controller.current.signal});setTurns(t=>[...t.slice(0,-1),{question:q,answer}]);
  }catch(e){if(!controller.current.signal.aborted){setTurns(t=>t.slice(0,-1));setQuestion(q);const text=message(e);setError(text);onError(text);}}finally{setBusy(false);}}
  return <div className={`chat-workspace ${home?"home-chat-active":""}`}><div className="chat-scope" data-tour="chat-scope"><ShieldCheck size={15}/><span>{preview?"Example transcript search · no AI request":configured?"Answers use this lesson only":"Transcript search · live AI is not connected"}</span></div>{!turns.length?(emptyState||<div className="chat-empty"><StudyAvatar reference/><h2>{home?"How can I help?":"How can I help?"}</h2><p>{configured?"Ask about this lesson.":"Search for a word or topic in this transcript. DarsLoop returns matching teacher passages."}</p>{actions}<div className="suggested-questions">{(lesson.demo?["What did the teacher say about revision?","Where was adab explained?","How do I catch up after an absence?"]:(lesson.artifacts?.notes.slice(0,3).map(n=>`What did the teacher say about “${n.heading}”?`)||[])).map(q=><button key={q} onClick={()=>void ask(q)}>{q}<ArrowUpRightMini/></button>)}</div></div>):<div className="chat-messages" aria-live="polite">{turns.map((t,i)=><article className="chat-turn" key={i}><div className="student-message"><span className="mini-label">YOU</span><p dir="auto">{t.question}</p></div><div className="assistant-message"><StudyAvatar small reference/><div><span className="mini-label">{t.answer?.mode==="excerpt"?"TEACHER PASSAGES · TEXT SEARCH":"AI ANSWER · THIS LESSON"}</span>{t.answer?<>{t.answer.blocks.map((b,j)=><div key={j} className="answer-block"><p dir="auto">{b.text}</p><Evidence evidence={b.evidence} lesson={lesson} onPlay={onPlay}/></div>)}{t.answer.message&&<p className={`answer-message ${t.answer.blocks.length?"muted":""}`} role={t.answer.status==="temporarily_unavailable"?"alert":undefined}>{t.answer.message}</p>}{t.answer.status==="temporarily_unavailable"&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void ask(t.question)}><ArrowCounterClockwise size={16}/>Retry question</button>}</>:<p className="thinking"><LoaderCircle size={16} className="spin"/> Finding the lesson passage…</p>}</div></div></article>)}<div ref={bottom}/></div>}
  {error&&<p className="lesson-inline-error chat-inline-error" role="alert"><WarningCircle size={16}/>{error}</p>}<form className={`chat-composer ${home?"home-composer":""}`} data-tour="home-composer" onSubmit={e=>{e.preventDefault();void ask(question);}}><label className="sr-only" htmlFor="class-question">Ask about this lesson</label><textarea id="class-question" rows={home?1:2} maxLength={1000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about this lesson…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(question);}}}/><div className="home-composer-footer">{tools}<div className="home-composer-actions">{composerActions}<button className="send-button" disabled={busy||question.trim().length<2} aria-label="Send question"><ArrowUp size={home?22:20}/></button></div></div></form><p className="composer-caption">{home?"Answers use your lesson. Ask a teacher for religious guidance.":"Answers use this lesson. Ask your teacher for religious guidance."}</p>
  </div>;
}
function ArrowUpRightMini(){return <ArrowRight size={15}/>;}
export function Practice({lesson,onPlay,onReviewed,onError,focusItemId,preview=false,scenePaused=false}:{lesson:Lesson;scenePaused?:boolean;onPlay:(time:number)=>void;onReviewed:(r:Review)=>void;onError:(s:string)=>void;focusItemId:string|null;preview?:boolean}) {
  const supported=availablePractice(lesson),focused=supported.find(item=>item.id===focusItemId);
  const initialKind=focused?.kind||"quiz";
  const [kind,setKind]=useState<"quiz"|"flashcard"|"test">(initialKind);
  const [index,setIndex]=useState(Math.max(0,supported.filter(item=>item.kind===initialKind).findIndex(item=>item.id===focusItemId)));
  const [revealed,setRevealed]=useState(false),[choice,setChoice]=useState<string|null>(null);
  const [result,setResult]=useState<{correct:boolean;review:Review}|null>(null),[busy,setBusy]=useState(false),[finished,setFinished]=useState(false),[error,setError]=useState("");
  const [saved,setSaved]=useState<Record<string,{correct:boolean;review:Review}>>({}),[testOpen,setTestOpen]=useState(false);
  const busyRef=useRef(false);
  const quiz=supported.filter(item=>item.kind==="quiz"),items=supported.filter(item=>item.kind===kind),item=items[index];
  function reset(){setRevealed(false);setChoice(null);setResult(null);setError("");}
  useEffect(()=>{const focus=availablePractice(lesson).find(item=>item.id===focusItemId);if(!focus)return;setKind(focus.kind);setIndex(Math.max(0,availablePractice(lesson).filter(item=>item.kind===focus.kind).findIndex(item=>item.id===focusItemId)));reset();setFinished(false);setSaved({});},[focusItemId,lesson.id,lesson.version]);
  async function review(remembered?:boolean){
    if(!item||busyRef.current||result||kind==="test"||kind==="quiz"&&choice===null)return;
    busyRef.current=true;setBusy(true);setError("");
    try {
      const response=preview?exampleReview(lesson,item,kind==="quiz"?choice===item.answer:remembered===true):await api<{correct:boolean;review:Review}>(`/api/lessons/${lesson.id}/review`,{method:"POST",body:JSON.stringify({itemId:item.id,version:lesson.version,...(kind==="quiz"?{answer:choice}:{remembered})})});
      setResult(response);setSaved(current=>({...current,[item.id]:response}));setRevealed(true);if(!preview)onReviewed(response.review);
    }catch(failure){const text=message(failure);setError(text);onError(text);}finally{busyRef.current=false;setBusy(false);}
  }
  function change(next:"quiz"|"flashcard"|"test"){if(busyRef.current)return;setKind(next);setIndex(0);reset();setFinished(false);setSaved({});}
  const correct=Object.values(saved).filter(response=>response.correct).length;
  return <div className="practice-workspace lesson-practice-reference" data-tour="practice">
    <div className="tab-intro"><p className="eyebrow">{lesson.demo?"PREPARED FICTIONAL PRACTICE":"AI PRACTICE · FROM THIS LESSON"}</p><h2>Practise what you learned.</h2><p>Try an answer, then return to the explanation.</p></div>
    <div className="lesson-practice-mode practice-mode" role="group" aria-label="Practice type"><button type="button" aria-pressed={kind==="quiz"} onClick={()=>change("quiz")} disabled={busy}><CheckCircle size={17}/>Quiz</button><button type="button" aria-pressed={kind==="flashcard"} onClick={()=>change("flashcard")} disabled={busy}><Layers size={17}/>Flashcards</button><button type="button" aria-pressed={kind==="test"} onClick={()=>change("test")} disabled={busy}><ClipboardText size={17}/>Lesson test</button></div>
    {kind==="test"?<div className="lesson-test-start"><span className="lesson-test-icon"><ClipboardText size={35}/></span><h3>Try the lesson without hints.</h3><p>Answer {quiz.length} available {quiz.length===1?"question":"questions"}. Your results and supporting passages appear after you submit.</p><button type="button" className="button primary" disabled={!quiz.length||preview} onClick={()=>setTestOpen(true)}>Start lesson test<ArrowRight size={16}/></button><small>{preview?"The example offers Quiz and Flashcards without saving. Your own lessons also have a saved test.":"Untimed practice from one lesson. This is not an official or full-course exam."}</small></div>
    :!items.length?<div className="empty-state"><Layers size={30}/><h3>No supported {kind==="quiz"?"quiz questions":"flashcards"} yet.</h3><p>Only clear, supported lesson points become practice.</p></div>
    :finished?<div className="practice-finished"><span className="success-ring"><CheckCircle size={29}/></span><h3>Review complete.</h3><p>{kind==="quiz"?`${correct} of ${Object.keys(saved).length} answers correct.`:`You marked ${correct} of ${Object.keys(saved).length} cards as remembered.`}</p><p>{preview?"Example responses are not saved.":"Your responses are saved privately. Missed points return sooner."}</p>{kind==="flashcard"&&<small>Card recall is your own check, separate from quiz marks.</small>}<button type="button" className="button secondary" onClick={()=>{setIndex(0);reset();setFinished(false);setSaved({});}}>Practise again<ArrowCounterClockwise size={16}/></button></div>
    :item&&<article key={item.id} className={`practice-card ${kind==="flashcard"?"flashcard":""} ${revealed?"card-revealed":""}`}>
      <div className="practice-card-top"><span className="mini-label">{kind==="quiz"?"LESSON QUESTION":"RECALL BEFORE REVEALING"}</span><span className="question-count">{index+1}<i> / {items.length}</i></span></div>
      <div className="practice-progress" aria-label={`${kind==="quiz"?"Question":"Card"} ${index+1} of ${items.length}`}><span style={{width:`${(index+1)/items.length*100}%`}}/></div>
      <h3 dir="auto">{item.question}</h3>
      {kind==="quiz"?<div className="quiz-choices">{item.choices.map((option,position)=><button type="button" key={`${option}-${position}`} aria-pressed={choice===option} disabled={!!result||busy} className={`${choice===option?"chosen":""} ${result&&option===item.answer?"correct-choice":""} ${result&&choice===option&&!result.correct?"wrong-choice":""}`} onClick={()=>setChoice(option)}><span>{String.fromCharCode(65+position)}</span><span dir="auto">{option}</span>{result&&option===item.answer&&<Check size={18}/>}</button>)}</div>
      :<div className={`flashcard-answer ${revealed?"is-flipped":""}`}>{revealed?<><span className="mini-label">CARD ANSWER · FROM THE LESSON</span><p dir="auto">{item.answer}</p></>:<div className="card-back-mark"><BookOpen size={34}/><p>Bring the explanation to mind.<br/>Then reveal the answer.</p></div>}</div>}
      {revealed&&<div aria-live="polite" className={`practice-feedback ${result&&!result.correct?"feedback-revisit":""}`}><strong>{result?kind==="flashcard"?result.correct?"Marked as remembered":"Saved to revisit":result.correct?"Correct":"Let’s revisit this point":"Compare with the lesson"}</strong>{kind==="quiz"&&result&&<p className="correct-answer-text" dir="auto">{item.answer}</p>}<Evidence evidence={item.evidence} lesson={lesson} onPlay={onPlay}/>{result&&<p className="small-text muted">{preview?"Example · not saved":`Next review: ${result.review.intervalDays===0?"in 10 minutes":`in ${result.review.intervalDays} ${result.review.intervalDays===1?"day":"days"}`}.`}</p>}</div>}
      {error&&<p className="lesson-inline-error" role="alert"><WarningCircle size={16}/>{error}</p>}
      <div className="practice-actions">{result?<button type="button" className="button primary" onClick={()=>{if(index+1>=items.length)setFinished(true);else{setIndex(current=>current+1);reset();}}}>{index+1>=items.length?"Finish review":"Next"}<ArrowRight size={16}/></button>:kind==="quiz"?<button type="button" className="button primary" disabled={choice===null||busy} onClick={()=>void review()}>{busy?"Saving…":"Check answer"}<Check size={16}/></button>:!revealed?<button type="button" className="button primary" onClick={()=>setRevealed(true)}>Reveal answer<BookOpen size={16}/></button>:<><button type="button" className="button secondary" disabled={busy} onClick={()=>void review(false)}>Revisit this</button><button type="button" className="button primary" disabled={busy} onClick={()=>void review(true)}>{busy?"Saving…":"I remembered"}<Check size={16}/></button></>}</div>
    </article>}
    <p className="practice-footnote">{kind==="flashcard"?"Card recall is self-reported. ":""}Check important wording against your teacher’s audio.</p>
    {testOpen&&<div className="is-reference-review"><PracticeSession lesson={lesson} items={quiz} mode="test" title="Lesson test" returnLabel="Back to lesson" onClose={()=>setTestOpen(false)} onPlay={(_,time)=>onPlay(time)} onOpen={(_,itemId)=>{setTestOpen(false);change("quiz");setIndex(Math.max(0,quiz.findIndex(question=>question.id===itemId)));}} onReviewed={onReviewed} onError={onError}/></div>}
  </div>;
}

function Transcript({lesson,onPlay}:{lesson:Lesson;onPlay:(time:number)=>void}) {
  const [search,setSearch]=useState("");const shown=lesson.segments.filter(s=>s.text.toLowerCase().includes(search.toLowerCase()));
  return <div className="transcript-workspace"><div className="tab-intro"><p className="eyebrow">THE CAPTURED EXPLANATION</p><h2>Your class transcript.</h2><p>{lesson.demo?"Exact fictional script with timings from generated audio. This is not an ASR test.":"Machine transcript. Unclear passages are marked; other transcription errors may remain."}</p></div><label className="search-field"><Search size={17}/><span className="sr-only">Search transcript</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a word in this lesson…"/>{search&&<button className="icon-button" aria-label="Clear transcript search" onClick={()=>setSearch("")}><X size={15}/></button>}</label><div className="transcript-list">{shown.length?shown.map(s=><article key={s.id} className={`transcript-passage ${s.flags.length?"uncertain-passage":""}`}><button type="button" className="timestamp" aria-label={`Play transcript at ${formatTime(s.start)}`} onClick={()=>onPlay(s.start)}><Play size={11} weight="fill"/><bdi>{formatTime(s.start)}</bdi></button><div><p dir="auto">{s.text}</p>{s.flags.length>0&&<div className="uncertainty-label"><Headphones size={14}/>{s.flags.join(" · ")}. Replay before relying on this passage.</div>}</div></article>):<div className="empty-state"><Search/><h3>No matching words.</h3><p>Try another spelling or a shorter phrase.</p></div>}</div></div>;
}
function Sources({lesson,onPlay,onError}:{lesson:Lesson;onPlay:(time:number)=>void;onError:(s:string)=>void}) {
  const [segmentId,setSegmentId]=useState(lesson.segments.find(s=>/hadith|narration|حديث|حدیث/i.test(s.text))?.id||lesson.segments[0]?.id||"");
  const [wording,setWording]=useState(""),[language,setLanguage]=useState("ar"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [result,setResult]=useState<{status:string;message:string;candidates:Candidate[]}|null>(null);
  const busyRef=useRef(false),segment=lesson.segments.find(s=>s.id===segmentId);
  async function search(event:React.FormEvent){
    event.preventDefault();if(busyRef.current||!segment||segment.flags.length)return;
    busyRef.current=true;setBusy(true);setResult(null);setError("");
    try{setResult(await api(`/api/lessons/${lesson.id}/references`,{method:"POST",body:JSON.stringify({segmentId,wording,language,version:lesson.version})}));}
    catch(failure){const text=message(failure);setError(text);onError(text);}
    finally{busyRef.current=false;setBusy(false);}
  }
  return <div className="sources-workspace">
    <div className="tab-intro"><p className="eyebrow">SEPARATE REFERENCE LOOKUP</p><h2>Possible hadith sources.</h2><p>Search HadeethEnc for a wording match. A match does not confirm which narration your teacher meant or give a religious ruling.</p></div>
    <form className="source-form" onSubmit={search}>
      <label className="field">Choose a lesson passage<select disabled={busy} value={segmentId} onChange={event=>{setSegmentId(event.target.value);setWording("");setResult(null);setError("");}}>{lesson.segments.map(passage=><option key={passage.id} value={passage.id}>{formatTime(passage.start)} · {passage.text.slice(0,70)}</option>)}</select></label>
      {segment&&<div className="captured-quote"><span className="mini-label">CAPTURED WORDS · CHECK THE AUDIO</span><p dir="auto">{segment.text}</p><button type="button" className="timestamp" aria-label={`Play captured passage at ${formatTime(segment.start)}`} onClick={()=>onPlay(segment.start)}><Play size={12} weight="fill"/><bdi>{formatTime(segment.start)}</bdi><span>Listen</span></button></div>}
      {!!segment?.flags.length&&<p className="source-uncertain"><Headphones size={17}/><span>This passage has unclear wording. Replay it and choose a clear passage before looking up a source.</span></p>}
      {segment&&<button type="button" disabled={busy||!!segment.flags.length} className="text-link source-copy" onClick={()=>setWording(segment.text.slice(0,400))}>Use these captured words<ArrowRight size={15}/></button>}
      <label className="field">Words to look up<textarea disabled={busy} rows={3} required minLength={12} maxLength={400} value={wording} onChange={event=>setWording(event.target.value)} placeholder="Use at least three words from the passage above…" dir="auto"/></label>
      <label className="field source-language">Source language<select disabled={busy} value={language} onChange={event=>setLanguage(event.target.value)}><option value="ar">Arabic</option><option value="en">English</option><option value="ur">Urdu</option></select></label>
      {error&&<p className="lesson-inline-error" role="alert"><WarningCircle size={17}/>{error}</p>}
      <button className="button primary" disabled={busy||!wording.trim()||!segment||!!segment.flags.length}>{busy?<><LoaderCircle className="spin" size={17}/>Looking for source records…</>:<><Search size={17}/>Find possible sources</>}</button>
      <p className="source-privacy-note">Only these captured words are sent to the public reference provider. Source matches stay separate from your class answers and practice.</p>
    </form>
    {result&&<div aria-live="polite" className="source-results"><p className="source-result-message">{result.message}</p>{result.candidates.map(candidate=><article className="source-card" key={candidate.id}>
      <span className="mini-label">POSSIBLE WORDING MATCH · {candidate.gradePublisher}</span><h3 dir="auto">{candidate.title}</h3><blockquote dir="auto">{candidate.text}</blockquote>
      <dl><div><dt>Published grade from {candidate.gradePublisher}</dt><dd dir="auto">{candidate.grade}</dd></div>{candidate.collectionAttribution&&<div><dt>Source’s collection attribution</dt><dd dir="auto">{candidate.collectionAttribution}</dd></div>}<div><dt>Provider record ID (not a collection number)</dt><dd>{candidate.id}</dd></div></dl>
      <a href={candidate.url} target="_blank" rel="noreferrer" className="text-link arrow-link">Open the publisher’s record<ExternalLink size={15}/></a><p className="source-record-note">Retrieved {new Date(candidate.retrievedAt).toLocaleDateString()}. Ask your teacher about the intended source and its meaning.</p>
    </article>)}</div>}
  </div>;
}
export function LessonView({lesson,tab,setTab,onBack,onPlay,onError,onShare,onDelete,onReviewed,configured,focusItemId,preview=false}:{lesson:Lesson;preview?:boolean;tab:LessonTab;setTab:(t:LessonTab)=>void;onBack:()=>void;onPlay:(time:number)=>void;onError:(s:string)=>void;onShare:()=>void;onDelete:()=>void;onReviewed:(r:Review)=>void;configured:boolean;focusItemId:string|null}) {
  const [teacherCheck,setTeacherCheck]=useState(false);
  const [retrying,setRetrying]=useState(false);const retryRef=useRef(false);
  const tabs:[LessonTab,string,React.ReactNode][]=[["catchup","Catch me up",<Headphones key="c" size={16}/>],["notes","Notes",<BookOpen key="n" size={16}/>],["ask","Ask this lesson",<MessageCircle key="a" size={16}/>],["practice","Practice",<Layers key="p" size={16}/>],["transcript","Transcript",<Headphones key="t" size={16}/>],["sources","References",<Search key="s" size={16}/>]];
  function exportNotes(){if(!lesson.artifacts||lesson.noteOptions?.enabled===false)return;const a=lesson.artifacts;const text=`# ${lesson.title}\n\n${lesson.demo?"Prepared fictional example":"AI-generated lesson notes"}\n\n`+a.notes.map(n=>`## ${n.heading}\n\n${n.text}\n\n`+n.evidence.map(c=>{const s=lesson.segments.find(s=>s.id===c.segmentId);return `> ${c.quote}\n\nAudio time: ${s?formatTime(s.start):"unavailable"} · transcript v${lesson.version}\n`;}).join("\n")).join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/markdown"}));const link=document.createElement("a");link.href=url;link.download="DarsLoop-lesson-notes.md";link.click();URL.revokeObjectURL(url);}
  async function retry(){if(retryRef.current||lesson.shared||lesson.demo||preview)return;retryRef.current=true;setRetrying(true);try{await api(`/api/lessons/${lesson.id}`,{method:"POST",body:JSON.stringify({action:"retry"})});window.dispatchEvent(new Event("darsloop-refresh"));}catch(failure){onError(message(failure));}finally{retryRef.current=false;setRetrying(false);}}
  return <div className="lesson-view"><button type="button" className="back-link" onClick={onBack}><ArrowLeft size={16}/> {preview?"Back to DarsLoop":"All lessons"}</button><div className="lesson-heading" data-tour="lesson-heading"><div className="lesson-title-group"><span className="lesson-title-icon" aria-hidden="true"><FileAudio size={32}/></span><div><h1 dir="auto">{lesson.title}</h1><div className="lesson-meta"><span className="course-label">{lesson.course}</span><span><Headphones size={14}/><bdi>{formatTime(lesson.duration)}</bdi> audio</span>{lesson.shared&&<span><Users size={14}/>Shared with you</span>}</div></div></div><div className="lesson-actions">{!!lesson.segments.length&&<button className="button secondary small" onClick={()=>setTeacherCheck(true)}><Headphones size={16}/>Teacher check</button>}<button type="button" className="icon-button" onClick={exportNotes} disabled={!lesson.artifacts?.notes.length||lesson.noteOptions?.enabled===false} aria-label="Download notes"><ArrowDownToLine size={19}/></button>{!preview&&!lesson.shared&&<><button type="button" className="button secondary small" onClick={onShare} disabled={lesson.status!=="ready"}><Users size={16}/>Share</button><button type="button" className="icon-button" onClick={onDelete} aria-label="Delete lesson"><Trash2 size={19}/></button></>}</div></div>
  {lesson.demo&&<div className="example-banner"><span>FICTIONAL EXAMPLE</span><p>Prepared notes and practice · synthetic audio · no live AI result or learning claim</p></div>}
  {(lesson.status!=="ready"||!!lesson.error)&&<div className={`processing-banner ${lesson.status==="failed"?"processing-failed":""}`} role="status"><div>{lesson.status==="failed"?<WarningCircle size={23}/>:<BookOpen size={23}/>}</div><div><strong>{lesson.transcriptionComplete?"Your transcript is ready.":lesson.status==="failed"?"Your lesson needs another try.":lesson.stage||"Preparing your lesson…"}</strong><p>{lesson.error||"Your audio is saved. Listen while your study material is prepared."}</p></div>{(lesson.status==="failed"||lesson.status==="ready"&&!!lesson.error)&&!lesson.shared&&!lesson.demo&&!preview&&<button type="button" className="button secondary small" disabled={retrying} onClick={()=>void retry()}>{retrying?"Retrying…":lesson.transcriptionComplete?"Retry study material":"Try again"}<ArrowCounterClockwise size={16}/></button>}</div>}
  <div className="lesson-tabs" data-tour="lesson-tabs" role="tablist" aria-label="Lesson views">{tabs.map(([key,label,icon])=><button role="tab" id={`tab-${key}`} aria-controls={`panel-${key}`} aria-selected={tab===key} tabIndex={tab===key?0:-1} key={key} onClick={()=>setTab(key)} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();const i=tabs.findIndex(t=>t[0]===key);const next=tabs[(i+(e.key==="ArrowRight"?1:tabs.length-1))%tabs.length][0];setTab(next);document.getElementById(`tab-${next}`)?.focus();}}}>{icon}{label}</button>)}</div>
  <section className="lesson-panel" role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>{!lesson.segments.length?<div className="empty-state"><FileAudio size={32}/><h3>{lesson.status==="failed"?"Your audio is still saved.":"Your recording is here."}</h3><p>{lesson.status==="failed"?"Study material couldn’t be prepared. You can still listen to the original recording below.":"Your transcript and study material will appear when processing finishes. You can listen below."}</p></div>:<>{tab==="catchup"&&<CatchUp lesson={lesson} onPlay={onPlay}/>} {tab==="notes"&&<Notes lesson={lesson} onPlay={onPlay}/>} {tab==="ask"&&<Chat lesson={lesson} onPlay={onPlay} onError={onError} configured={configured} preview={preview}/>} {tab==="practice"&&<Practice lesson={lesson} onPlay={onPlay} onReviewed={onReviewed} onError={onError} focusItemId={focusItemId} preview={preview}/>} {tab==="transcript"&&<Transcript lesson={lesson} onPlay={onPlay}/>} {tab==="sources"&&(preview?<div className="tab-intro"><p className="eyebrow">SEPARATE SOURCE LOOKUP</p><h2>A source needs actual wording.</h2><p>This fictional lesson has no hadith quotation to look up. In your own lesson, choose captured words to find possible publisher records. These matches stay separate from class answers.</p><Link className="button secondary" href="/signin">Start your own lesson<ArrowRight size={16}/></Link></div>:<Sources lesson={lesson} onPlay={onPlay} onError={onError}/>)}</>}</section>{teacherCheck&&<TeacherCheck lesson={lesson} onClose={()=>setTeacherCheck(false)}/>}</div>;
}
