"use client";
import { useState } from "react";
import { FilePdf, DownloadSimple, MagnifyingGlass, ArrowSquareOut, X } from "@phosphor-icons/react";
import { pdfSourceUrl } from "@/lib/source-passages";
import type { Lesson } from "@/lib/types";
import { SourceExcerpt } from "./source-excerpt";
import styles from "./pdf-pages.module.css";
export function PdfPages({lesson}:{lesson:Lesson}){
  const [query,setQuery]=useState("");const all=lesson.pdfPages??[],term=query.trim().toLocaleLowerCase(),pages=all.filter(p=>!term||p.text.toLocaleLowerCase().includes(term)),pageCount=lesson.sourcePageCount??all.length;
  return <div className={styles.workspace}><div className={styles.intro}><p className="eyebrow">YOUR PRIVATE SOURCE</p><h2>PDF pages.</h2><p>Selectable text from {pageCount} PDF pages. Short extracted lines wrap together here for easier reading. Open the original to check layout, symbols and important wording. Scanned text is not extracted.</p><div className={styles.actions}><a className="button secondary small" href={pdfSourceUrl(lesson)} target="_blank" rel="noreferrer"><FilePdf size={17}/>Open original PDF</a><a className="button secondary small" href={pdfSourceUrl(lesson,undefined,true)}><DownloadSimple size={17}/>Download</a></div></div><label className={styles.search} data-tour="source-search"><MagnifyingGlass size={17}/><input aria-label="Search PDF pages" placeholder="Find a word in this PDF…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="Clear PDF search" onClick={()=>setQuery("")}><X size={15}/></button>}</label><p className={styles.count} role="status">{term?`${pages.length} matching ${pages.length===1?"page":"pages"}`:`${all.length} ${all.length===1?"page":"pages"} available`}</p><div className={styles.list}>{pages.map(page=><SourceExcerpt key={page.id} label={`Page ${page.page}`} text={page.text} flags={page.flags} actions={<a className={styles.pageLink} href={pdfSourceUrl(lesson,page.page)} target="_blank" rel="noreferrer" aria-label={`Open PDF page ${page.page}`}><FilePdf size={13}/>Open page<ArrowSquareOut size={12}/></a>}/>)}{!pages.length&&<p className={styles.empty}>{all.length?"No matching pages. Try a shorter phrase.":"No selectable pages are saved for this PDF."}</p>}</div></div>;
}
